version: '3.9'

services:
  dev-server:
    container_name: dev-server
    environment:
      NODE_ENV: development
    build:
      context: ./server
      dockerfile: ./Dockerfile
      target: development
    ports:
      - '4000:4000'
      - '9229:9229'
    command: npm run start:dev
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - super-db-postgres
    networks:
      - super-net
    restart: unless-stopped
  super-db-postgres:
    container_name: super-db-postgres
    image: postgres:14-alpine3.15
    environment:
      POSTGRES_PASSWORD: javaIs_The100BesT!
      POSTGRES_USER: postgres
      POSTGRES_DB: db_supers
      PG_DATA: /var/lib/postgresql/data
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - super-net
    tty: true
    restart: always
  adminer:
    image: adminer
    container_name: adminer-docker
    depends_on:
      - super-db-postgres
    ports:
      - '8080:8080'
    networks:
      - super-net
    restart: on-failure

volumes:
  pgdata:
  dev-server:

networks:
  super-net:
    driver: bridge